### ISSUE TITLE
Please make this usable for non-programmers.

### ISSUE THREAD

**Issue by Someonemustnothavethis** [cgfasttrack/lazyviewport#1]
What am I supposed to do with this?  I know where .py files go in Blender but I can't download the thing.  Clicking on it just shows me a pile of code.  Remember that many (most?) Blender users are artists and see this code stuff as just a string of incomprehensible gibberish.  That doesn't mean we're stupid, we're just not programmers and have no interest in learning it.
Thanks.
Bob

**Comment by robbybranham** [comment]
Hi Bob, we have a tutorial on our website for members that walks you through the process. If your not a member, you are still welcome to use it. 

Sounds like you have never downloaded something from github before? 

You can download using the green button labled "code", in the drop down menu choose download zip. Then extract that zip file and then install this as as a Blender add on.

**Comment by robbybranham** [comment]
We opened up a chapter video that walks you through the process. 

https://www.cgfasttrack.com/chapters/blender102-0055-lazy-viewport-add-on

What does it do? 
It uses the standard G, R, S hotkeys to work with the viewport tools, so you don't have to use the snapping hotkeys X, Y, Z while working.

**Comment by cgfasttrack** [comment]
Also updated the README section with instructions. Enjoy.
