### ISSUE TITLE
Doesn't work in blender 3.2.1

### ISSUE THREAD

**Issue by agariomaster10** [cgfasttrack/lazyviewport#14]
downloads and goes into the addons folder just fine but does not show on addons list in the application.

**Comment by cgfasttrack** [comment]
Hello! We have tested and have many currently using it in Blender 3.2.1 and newer versions, no issues found. You may need to extract it from its zip file and then click "install" on the addons tab. It should not attempt to move its folder as the folder is not associated with the addon. More info and instructions on how to install on "code" page under README. If you are following the sword in the stone tutorial, there is a chapter that shows how to install it as well.
