### ISSUE TITLE
Unable to move objects while anim player running

### ISSUE THREAD

**Issue by God-Renech** [cgfasttrack/lazyviewport#16]
Unable to move objects while anim player running

**Comment by cgfasttrack** [comment]
Blender does not support moving objects while anim player is running.

**Comment by God-Renech** [comment]
blender can do that after I've removed this addon

**Comment by cgfasttrack** [comment]
To clarify, the G hotkey, when not using the lazy viewport add-on does not require a visible handle and automatically moves the object. 

This specific add-on remaps the hotkeys of G R and S to the viewport toolbar Move Rotate and Scale. 

**The viewport toolbar don't show up in animation mode, with or without the lazy viewport add-on.**  

There may be a way to enable this in Blender, I am not aware of any.
