### ISSUE TITLE
[BUG] Enable/Disable Addon Broken

### ISSUE THREAD

**Issue by Cronoo** [cgfasttrack/lazyviewport#2]
so the bug i have found is if you install this enable it then disable the addon in blender 2.90.1 it stays active in a save file even if u delete it from the users folder and blenders install location folder.

i was going to test the addon to see if i liked it better than doing it the default way so i wanted to disable it to compare vs the old way.

i added my .blend files for the project the addon is removed from but still active in

[Small Robot.zip](https://github.com/cgfasttrack/lazyviewport/files/5436327/Small.Robot.zip)

**Comment by Cronoo** [comment]
oh and it seems to only be stuck in scale but move is back to default

**Comment by cgfasttrack** [comment]
Hi Cronoo, 

This is not something we are able to reproduce. We tried a several computers and have asked others if they have ran into the issue and have not had any lucky. 

We tested your file as well. Not able to reproduce. 

Some things to try: 
1. Are you using the save preferences button before closing blender? 
2. Also, the move, rotate and scale button will still be active until you switch over to selection mode. The hotkeys however will still work as the default.

**Comment by Cronoo** [comment]
sorry re reading my first post i didn't go into enough detail sorry about that.
and i found a way to reproduce it,

I saved pref between all the on of switching,

Turn the addon on and then hit scale or move or rotate on a obj, then turn the addon off and the last gizmo you used will stay stuck on if you turn the addon back on they start acting normally till you turn it off again, moving the save file to another computer that dosent have the addon still has the stuck on gizmo, i cant seem to find a way to remove the forever stuck on gizmo.

**Comment by cgfasttrack** [comment]
When the tool is disabled, currently that is all it does it disable the shortcuts overrides. It does not do any scene modifications on disabling. 

Try selecting the select tool (first tool in the top left of the 3D view, above the move, rotate, scale gizmos). This will deactivate any currently activated tool.

**Comment by Cronoo** [comment]
/facepalm yep that fixed it, sorry for all the trouble.
