### ISSUE TITLE
Extrude shortcut defaults to Extrude Region when Extrude along Normals is set

### ISSUE THREAD

**Issue by shwashbuckle** [cgfasttrack/lazyviewport#8]
Hi, not sure if this is actually an issue or not but when I manually set the Extrude toolbar option to Extrude along normals and then later press the E key it tries to Extrude region instead.  The only workaround I've found so far is to not use the shortcut key at all and select the extrude option from the toolbar.  Sometimes if I right mouse click and then Ctrl+Z to undo the new faces it will go into Extrude along normals as originally expected and from there I can extrude along normals.  Also not sure if this happening because of the Lazy Viewport plug-in or not but only started to notice it after installing it.

I am running Blender version 2.91.2.

Love the plug-in btw - makes G, S, R much easier!

**Comment by cgfasttrack** [comment]
Hi, 

This sounds like Blender is functioning correctly. The viewport gizmos do not function with the extrusion tool. Pressing E always communicates with the standard extrude tool, not the extrude along normals.

**Comment by shwashbuckle** [comment]
Yes sorry cgfasttrack, serious case of PEBKAC here on my part.  Please ignore my stupidity.  Had to hit the Blender manual on this one to remind me that Extrude along normals shortcut is available via Alt+E and not E.
